### PR TITLE
keep `AudioSubsystem` alive while `AudioDevice`s or `AudioStream`a are alive

### LINKED ISSUE #79: Memory corruption in SDL Audio
Hi, i am porting my SDL2 code to SDL3 code. It will check that the audio is initialized or not. If not, the program will skip the audio portion. Otherwise the audio is played using queue instead of callback.

However, recently found out that in the line "_let audio_stream = if let Ok(audio_subsystem) = audio_subsystem {_" is causing issue. The audio_subsystem will be deallocated too early and causing ACCESS_VIOLATION or HEAP_CORRUPTION error. This can be solved by changing to "_let audio_stream = if let Ok(**ref** audio_subsystem) = audio_subsystem {_". 

This issue did not happened in SDL2 crate but in SDL3 crate.

Shown below is the code to demonstrate the problem.

```rust

use sdl3::Error;
use sdl3::audio::{AudioFormat, AudioSpec, AudioStream};
use std::time::Duration;

fn gen_wave(bytes_to_write: i32) -> Vec<i16> {
    // Generate a square wave
    let tone_volume = 1_000i16;
    let period = 44100 / 256;
    let sample_count = bytes_to_write;
    let mut result = Vec::new();

    for x in 0..sample_count {
        result.push(if (x / period) % 2 == 0 {
            tone_volume
        } else {
            -tone_volume
        });
    }
    result
}

fn main() -> Result<(), Error> {
    let sdl_context = sdl3::init()?;
    let audio_subsystem = sdl_context.audio();

    let desired_spec = AudioSpec {
        freq: Some(44100),
        channels: Some(1),
        format: Some(AudioFormat::s16_sys()),
    };

    // To fix the crash
    // let audio_stream = if let Ok(ref audio_subsystem) = audio_subsystem {
    let audio_stream = if let Ok(audio_subsystem) = audio_subsystem {
        let audio_device = audio_subsystem.open_playback_device(&desired_spec)?;
        let stream = AudioStream::open_device_stream(audio_device.id(), Some(&desired_spec))?;
        stream.resume().expect("Unable to resume playback");
        Some(stream)
    } else {
        None
    };


    if let Some(stream) = &audio_stream {
        // Put data to stream
        let wave = gen_wave(44100 * 2);

        let mut byte_buffer: Vec<u8> = Vec::new();
        for &item in &wave {
            let data = item.to_ne_bytes();
            byte_buffer.push(data[0]);
            byte_buffer.push(data[1]);
        }
        let _ = stream.put_data(&byte_buffer);
    }
    
    // Play for 1.0 seconds
    std::thread::sleep(Duration::from_millis(1000));

    Ok(())
}

```

### PR DESCRIPTION
**Pull request by antonilol**
breaking change because some functions allowed creating streams or devices without requiring an `AudioSubsystem`

fixes #79

### CODE REVIEW

File: src/sdl3/audio.rs [hunk 1]
```diff
@@ -656,8 +667,11 @@ impl AudioDevice {
...
     }
 
-    pub fn new(device_id: AudioDeviceID) -> Self {
-        AudioDevice { device_id }
+    pub fn new(device_id: AudioDeviceID, audio_subsystem: AudioSubsystem) -> Self {
+        AudioDevice {
+            device_id,
+            audio_subsystem,
+        }
     }
```
Comment (antonilol) [inline src/sdl3/audio.rs:747]: Should this be part of the public API?

**Comment by antonilol** [comment]
I will later today check if this actually fixes the problem

Edit: it does

File: src/sdl3/audio.rs [hunk 2]
```diff
@@ -1040,17 +1106,20 @@ impl AudioStream {
...
     ) -> Result<Self, Error> {
-        Self::new(device_spec, Some(app_spec))
+        Self::new(device_spec, Some(app_spec), audio_subsystem)
     }
 
     /// Create an `AudioStream` for this device with the specified spec.
     /// This device will be closed when the stream is dropped.
     /// The device begins paused, so you must call `stream.resume()` to start playback.
     #[doc(alias = "SDL_OpenAudioDeviceStream")]
+    #[deprecated = "use `device.open_device_stream(spec)` (where device is an `AudioDevice`) instead"]
```
Comment (antonilol) [inline src/sdl3/audio.rs:1174]: What should happen with this function? It is almost identical to `AudioDevice::open_device_stream` (I added this in 57069b243d424a46b6bb99e88fa83ef1b0d4d5ec because it has 2 parameters that are fields of `AudioDevice`, so it is easier to call with only 1 parameter excluding `self`).

Comment (antonilol) [reply src/sdl3/audio.rs:1174]: After a successful `SDL_OpenAudioDeviceStream` call SDL will close the device when the stream is closed, so it makes sense to me to take an `AudioDevice` by value (`self` parameter there) in Rust.
